name: MegaSkyWars
version: 1.0
main: me.BlackKnight625.MegaSkyWars.Main
author: BlackKnight625
description: A grand mini-game for a bunch of players
api-version: 1.13
commands:
   oi:
      description: Debugging tool
      usage: /oi
      permission: <MegaSkyWars>.oi
      permission-message: You don't have <permission>
   oioi:
      description: 2nd Debugging tool
      usage: /oioi
      permission: <MegaSkyWars>.oioi
      permission-message: You don't have <permission>
   team:
      description: Join a team
      usage: /team (player) join TEAMCOLOR
      permission: <MegaSkyWars>.team
      permission-message: You don't have <permission>
   structure:
      description: Create a structure
      usage: /structure STRUCTURE_TYPE
      permission: <MegaSkyWars>.structure
      permission-message: You don't have <permission>
   friendlymob:
      description: Creates a friendly mob
      usage: /friendlymob ENTITY_TYPE
      permission: <MegaSkyWars>.friendlymob
      permission-message: You don't have <permission>
   spawnores:
      description: Creates ores around the player
      usage: /spawnores OreType ReplacedBlockType radius ammount
      permission: <MegaSkyWars>.friendlymob
      permission-message: You don't have <permission>